# Generated by Django 2.0.5 on 2018-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('occupation', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
